name: a9650615/ms-teams-notify
description: Microsoft Teams Github Actions integration
author: a9650615
inputs:
  github-token:
    required: true
    description: Github token
  webhook-uri:
    required: true
    description: MS Teams webhook URI
runs:
  using: node12
  main: dist/main/index.js